# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Runs all the tests"
  lane :test do
    scan(
      workspace: "Template_iOSUIKit.xcworkspace",
      scheme: "Template_iOSUIKit",
      configuration: "Debug",
      device: "iPhone 12",
      code_coverage: true,
      derived_data_path: "build/fastlane/derived_data",
      buildlog_path: "build/fastlane/scan_build_log",      
      output_directory: "static_html/test_result",
      # test_without_building: true,
      # max_concurrent_simulators: 1,
      # open_report: true,
      skip_build: true,
      output_types: "html",
      output_files: "index.html"
    )

    slather(
      html: true,
      workspace: "Template_iOSUIKit.xcworkspace",
      proj: "Template_iOSUIKit.xcodeproj",
      scheme: "Template_iOSUIKit",
      build_directory: "build/fastlane/derived_data",
      output_directory: "static_html/coverage_result",
      ignore: "Pods/**",
      # cobertura_xml: true,
      # verbose: true
    )
  end
end