rm -rf *.xcodeproj
rm -rf *.xcworkspace
rm -rf Pods/
rm -rf Podfile.lock
rm -rf Gemfile.lock
rm -rf R.generated.swift
rm -rf build/fastlane
rm -rf static_html/coverage_result
rm -rf static_html/docs
rm -rf static_html/test_result
